// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkE8sMp3fLi7iQI2RpqrIZYis0wYLZitY',
    appId: '1:270710283358:web:5e8b0f85f17893785ca8cf',
    messagingSenderId: '270710283358',
    projectId: 'codeclause-68ef5',
    authDomain: 'codeclause-68ef5.firebaseapp.com',
    storageBucket: 'codeclause-68ef5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdFZ-K6I4za7M44ExDtxG24YIPbidAfEQ',
    appId: '1:270710283358:android:6046056bf0265cdb5ca8cf',
    messagingSenderId: '270710283358',
    projectId: 'codeclause-68ef5',
    storageBucket: 'codeclause-68ef5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOzn8acznfPcwdOlamOl2ezYdV_zMVpuY',
    appId: '1:270710283358:ios:63a9b0812867c2675ca8cf',
    messagingSenderId: '270710283358',
    projectId: 'codeclause-68ef5',
    storageBucket: 'codeclause-68ef5.firebasestorage.app',
    iosClientId: '270710283358-uhj4bb0hjoqjonfimdtv1tikg3v6bqt9.apps.googleusercontent.com',
    iosBundleId: 'com.example.codeclause',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOzn8acznfPcwdOlamOl2ezYdV_zMVpuY',
    appId: '1:270710283358:ios:63a9b0812867c2675ca8cf',
    messagingSenderId: '270710283358',
    projectId: 'codeclause-68ef5',
    storageBucket: 'codeclause-68ef5.firebasestorage.app',
    iosClientId: '270710283358-uhj4bb0hjoqjonfimdtv1tikg3v6bqt9.apps.googleusercontent.com',
    iosBundleId: 'com.example.codeclause',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkE8sMp3fLi7iQI2RpqrIZYis0wYLZitY',
    appId: '1:270710283358:web:ce05057d3728bdbe5ca8cf',
    messagingSenderId: '270710283358',
    projectId: 'codeclause-68ef5',
    authDomain: 'codeclause-68ef5.firebaseapp.com',
    storageBucket: 'codeclause-68ef5.firebasestorage.app',
  );

}